/* ACTION TYPES */

// PLACE ORDER
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

// RESET STATE
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";
